version: "3.9"
services:
  migrate:
    build: ./
    volumes:
      - ./src:/app/src
      - ./package.json:/app/package.json
      - ./tsconfig.json:/app/tsconfig.json
      - ./knexfile.ts:/app/knexfile.ts
      - ./dev.env:/app/dev.env
      - ./test.env:/app/test.env