version: "3.9"
services:
  migrate:
    build: ./
    volumes:
      - ./src:/app/src
      - ./package.json:/app/package.json
      - ./tsconfig.json:/app/tsconfig.json
      - ./knexfile.ts:/app/knexfile.ts
    environment:
      DATABASE_URL: 'postgres://admin:devpassword@postgres:5432/dev_overview?sslmode=disable'